---
# image source is https://github.com/cf-platform-eng/pcf-examples/tree/master/src/docker
image: mirror.gcr.io/cfplatformeng/spacebears
imageTag: latest

spacebears:
  username: admin_db
  password: monkey123

service:
  type: LoadBalancer